### ISSUE TITLE
请问NODELIST(REASON)各个属性的含义？以及后序应该怎么操作？

### ISSUE THREAD

**Issue by vanetspark** [blcuicall/BLCU-HPC#10]
例如 QOSMaxGRESPerUser、JobHeldAdmin等词条的含义是什么，为什么在有卡的节点上始终无法申请成功等。

**Comment by chongruining** [comment]
QOSMaxGRESPerUser:达到每个用户限定的最大GPU数，JobHeldAdmin作业被系统管理员挂起。但由于目前slurm系统本身判定的问题，有些属性和真实原因是不匹配的，例如有CPU资源不足却显示JobHeldAdmin。后续可以检查出GPU以外的其他资源如CPU内存有无超出有现象。
