### ISSUE TITLE
安装sndfile

### ISSUE THREAD

**Issue by JuneAndJuly** [blcuicall/BLCU-HPC#11]
sudo apt-get install libsndfile1 
![image](https://user-images.githubusercontent.com/33370520/169701154-0a2952a8-8166-4d46-888e-29f2e1044b58.png)

**Comment by chongruining** [comment]
![image](https://user-images.githubusercontent.com/75966956/169706310-aa4c1f2d-d294-44fc-bacd-75eaa7189e98.png)
