### ISSUE TITLE
需要安装yum，但是没有root权限

### ISSUE THREAD

**Issue by chenyue-anon** [blcuicall/BLCU-HPC#12]
起因：安装bcolz出错，上网找资料发现需要安装其它依赖包，依赖包的安装方式基本方式都是yum install -y libffi-devel python-devel openssl-devel 
问题：安装yum的命令：sudo apt-get install yum 无权限

**Comment by chongruining** [comment]
yum是centos的默认包管理软件，Ubuntu使用apt进行包管理，目前已经安装libffi-dev、python-dev，请检查是否可以正常进行后续操作，若依然不行请提供所需依赖包的ubuntu版本名称或安装命令。

**Comment by chenyue-anon** [comment]
谢谢，我调低了python版本后安装成功了
