### ISSUE TITLE
在sbatch提交任务之后无法activate环境

### ISSUE THREAD

**Issue by JonnesLin** [blcuicall/BLCU-HPC#16]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/45222374/177881671-9d4ed5aa-2e2b-47da-9cf2-4ac33c538b93.png">
在sbatch提交任务之后，无法使用conda activate。但是在交互式的情况下，是可以的。

**Comment by chongruining** [comment]
可以提供sbatch的脚本吗？

**Comment by chongruining** [comment]
可以尝试重新激活一下环境
`# 重新进入虚拟环境
source activate
# 退出虚拟环境
conda deactivate`
再执行sbatch

**Comment by chongruining** [comment]
可以尝试重新激活环境
```
# 重新进入虚拟环境
source activate
# 退出虚拟环境
conda deactivate
```
再执行sbatch

**Comment by JonnesLin** [comment]
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/45222374/178036123-6efca6dd-2cc9-4972-959e-44f51d9132e8.png">
还是不行。你可以给我邮箱吗？我发script给你？

**Comment by chongruining** [comment]
chongruining@163.com
