### ISSUE TITLE
能出个教程讲讲怎么配置从集群服务器打开jupyter么

### ISSUE THREAD

**Issue by lunar333** [blcuicall/BLCU-HPC#19]
我在网上找了各种配置的教程，又是映射ip地址，又是改bash的，配置了好久都还是打不开jupyter（从anaconda打开jupyter）

**Comment by chongruining** [comment]
issue只负责解决集群出现的bug或必须管理员权限的依赖安装等问题，其他无关问题请自行解决。

**Comment by lunar333** [comment]
> issue只负责解决集群出现的bug或必须管理员权限的依赖安装等问题，其他无关问题请自行解决。

那我说一个涉及到服务器防火墙或者管理员权限的具体问题，我在按网上教程配置好后

使用了这个命令 ssh username@address_of_remote -L 127.0.0.1:1234:127.0.0.1:8888，按照网上说的便可以在 localhost:1234 直接访问远程的 jupyter notebook了。

我在浏览器输入localhost:1234并且刷新后，服务器出现报错如下：
 connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused

网上搜了这个报错，网友说是因为服务器没有装openssh-server，如下图所示：
![image](https://user-images.githubusercontent.com/103866630/198834031-a9fb1a01-fc72-4ec5-b299-7f17ab92f031.png)

我是在输入这个地址后，刷新浏览器，服务器才报的这个错误，说明本身我配置是对的，浏览器和服务器是有通信的，说明是服务器权限，或者防火墙设置的问题导致无法远程访问服务器jupyter

**Comment by chongruining** [comment]
openssh-server是已经安装的。原因是因防火墙设置无法用jupyter访问集群。集群是同学们公用的，安全设置是不能改的，你可以尝试在个人服务器上搭建jupyter。

**Comment by chongruining** [comment]
BLCU-HPC高性能计算集群旨在为同学们提供一个模型计算平台，请不要尝试在集群上进行任何个人服务的搭建与配置。

**Comment by lunar333** [comment]
> BLCU-HPC高性能计算集群旨在为同学们提供一个模型计算平台，请不要尝试在集群上进行任何个人服务的搭建与配置。

好的，我听朋友说有人用过服务器打开过jupter，我还以为是集群的
