### ISSUE TITLE
BLCU-HPC使用指南 http://hpc.litmind.ink 在校内也无法访问

### ISSUE THREAD

**Issue by summerwind0630** [blcuicall/BLCU-HPC#22]
BLCU-HPC使用指南 http://hpc.litmind.ink/
N.B.: 目前只支持校内访问

请问这个链接打不开是什么原因呢？我用的是实验室的网，BLCU网也打不开。
谢谢

**Comment by summerwind0630** [comment]
应该是防火墙问题，我打开了 ^^
btw,请问我们集群能访问外网进行爬虫吗？

**Comment by chongruining** [comment]
集群只供同学们进行模型计算等任务使用，请勿用作其他用途
