### ISSUE TITLE
连接提示密码过期，需要修改密码，但修改后还是连不上节点

### ISSUE THREAD

**Issue by YinChenzzZ** [blcuicall/BLCU-HPC#29]
连接学院集群的时候提示我的密码过期了，让我修改密码，但我在改过密码后还是连不上节点。
申请节点后输入新密码提示：
Permission denied, please try again.
输入旧密码提示：
You are required to change your password immediately (password expired)
Welcome to Ubuntu 20.04.4 LTS
...
WARNING: Your password has expired.
You must change your password now and login again!
passwd: Authentication token manipulation error
passwd: password unchanged
Connection to compute2 closed.

**Comment by TreemanCHou** [comment]
该问题是由于 Linux 密码更新机制和 NIS 系统未协作导致的。在密码过期后，系统设置的密码和更新机制并不会将密码信息同步至每一个节点。我们将会尝试解决该问题。

在此之前，用户在个人 `旧密码` 过期后，系统会强制让用户设置 `新密码`。在此之后，可以登录主节点，使用 yppasswd 指令再次更新密码。首先输入系统强制你更新的 `新密码`，然后再设置 `新新密码` 以在集群节点上同步。

```shell
$ yppasswd
NIS account information for user on admin.cmd.blculease 
enter old password: [输入当前密码（新密码）]
changing NIs password for szxw68136 on admin.cmd.blcuPlease 
enter new password: [更新密码（新新密码）]
Please retype new password: [再次输入，确认]
```
