### ISSUE TITLE
麻烦下载一下这几个包

### ISSUE THREAD

**Issue by JuneAndJuly** [blcuicall/BLCU-HPC#4]
![image](https://user-images.githubusercontent.com/33370520/166097409-a4c93777-2974-4e74-b46f-d393a72f8628.png)
extras/check_dependencies.sh: automake is not installed.
extras/check_dependencies.sh: autoconf is not installed.
extras/check_dependencies.sh: sox is not installed.
extras/check_dependencies.sh: gfortran is not installed
extras/check_dependencies.sh: neither libtoolize nor glibtoolize is installed
extras/check_dependencies.sh: subversion is not installed
extras/check_dependencies.sh: python2.7 is not installed
extras/check_dependencies.sh: Intel MKL does not seem to be installed.
 ... Run extras/install_mkl.sh to install it. Some distros (e.g., Ubuntu 20.04) provide
 ... a version of MKL via the package manager, but verify that it is up-to-date.
 ... You can also use other matrix algebra libraries. For information, see:
 ...   http://kaldi-asr.org/doc/matrixwrap.html
extras/check_dependencies.sh: Some prerequisites are missing; install them using the command:
  sudo apt-get install automake autoconf sox gfortran libtool subversion python2.7

**Comment by liuxin99** [comment]
已安装
