### ISSUE TITLE
为什么一直需要PD，明明有卡，

### ISSUE THREAD

**Issue by YKKKKKKK** [blcuicall/BLCU-HPC#5]
一直显示PD，明明有空余的卡，而且srun 交互式运行就可以拿到卡，sbatch就不行

<img width="902" alt="image" src="https://user-images.githubusercontent.com/38751297/166106573-66340b2e-9a80-4e09-b1d4-89badf51ceba.png">

**Comment by liuxin99** [comment]
最近sbatch还有些问题，请先按照群里孔学长说的方法使用，会尽快解决，请谅解~

**Comment by chongruining** [comment]
最近发现 sbatch 命令有点小问题，目前正在尝试解决，salloc 命令不受影响。大家在提交任务时如果遇到提交不上的情况可以尝试这样：
1. 使用 tmux 创建一个 session
2. 使用 salloc 申请资源
3. 申请到资源后，使用 srun 命令运行脚本。比如要运行 test.py 的，使用 srun python test.py 命令运行。
