### ISSUE TITLE
请问为什么集群更新之后一个2G的语料都out of memory？之前是可以跑的。

### ISSUE THREAD

**Issue by tomorrow-zy** [blcuicall/BLCU-HPC#6]

**Comment by tianlinyang** [comment]
请提供运行程序的脚本和错误信息截图。

**Comment by tomorrow-zy** [comment]
运行srun python xxx.py 后出现
![1651494127(1)](https://user-images.githubusercontent.com/58356035/166232832-da11a7e2-f47a-4937-80bb-481b98fd12a7.png)
