### ISSUE TITLE
想装一个库 但是需要root权限

### ISSUE THREAD

**Issue by zhaozhilin** [blcuicall/BLCU-HPC#7]
https://blog.csdn.net/qq_43153603/article/details/108051674
这是安装文档 最后一步需要root权限。求助
![image](https://user-images.githubusercontent.com/61971393/166213878-ea147ad3-c378-4a54-b3ee-1ca855d3f0db.png)

**Comment by tianlinyang** [comment]
已经安装。

Ref: https://abseil.io/docs/cpp/tools/cmake-installs#create-and-run-your-project
使用 hello_world.cc 测试如下：
$ module add abseil
$ mkdir build && cd build
$ cmake .. -DCMAKE_PREFIX_PATH=$ABSEIL_HOME && make
$ ./hello_world
