### ISSUE TITLE
需要安装一下mkl

### ISSUE THREAD

**Issue by JuneAndJuly** [blcuicall/BLCU-HPC#9]
extras/install_mkl.sh: Your system is using debian-style package management.
extras/install_mkl.sh: You must be root to install MKL.

Restart this script using the 'sudo' command, as:

  sudo extras/install_mkl.sh -sp debian intel-mkl-64bit-2020.0-088

We recommend adding the '-sp debian' options to skip the MKL and distro
detection, since this has already been done. This minimizes the number of
programs invoked with the root privileges to keep your system safe from
unexpected or erroneous changes. Also, if you are setting the CC environment
variable, sudo might not allow it to propagate to the command that it invokes.

Run the above sudo command now? [Y/n]:y
+ exec sudo extras/install_mkl.sh -sp debian intel-mkl-64bit-2020.0-088
![image](https://user-images.githubusercontent.com/33370520/166699330-f4b602c0-1948-4e37-8efa-b41cdd5080ee.png)

**Comment by chongruining** [comment]
请提供具体的下载链接和版本信息，或者所在下载后的路径

**Comment by JuneAndJuly** [comment]
sudo /data/private/szjs8402/workspace/kaldi/tools/extras/install_mkl.sh -sp debian intel-mkl-64bit-2020.0-088

**Comment by chongruining** [comment]
已安装
